services:
  # App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-project-app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    networks:
      - next-network
    depends_on:
      - postgres

  # PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: next-project-postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - next-network

  # adminer
  adminer:
    image: adminer
    container_name: next-project-adminer
    env_file:
      - .env
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - next-network
    depends_on:
      - postgres

# Volumes
volumes:
  postgres-data:

# Networks
networks:
  next-network:
    driver: bridge
